// Environment file generation.
// Replaces playbooks/templates/container.env.j2
//
// Output: ~/.config/containers/systemd/{name}.env

use std::fmt::Write as _;

use anyhow::Result;
use fs_node_core::state::desired::ServiceInstance;

/// Generate the .env file content for the given module instance.
/// All Jinja2 vars are already resolved in `instance.resolved_env`.
///
/// # Errors
///
/// Returns an error if string formatting fails (infallible in practice).
pub fn generate(instance: &ServiceInstance) -> Result<String> {
    let mut out = String::new();
    let _ = writeln!(out, "# Generated by fsn – {}", instance.class_key);
    out.push_str("# Do not edit manually – regenerated on every deploy\n\n");

    for (key, value) in &instance.resolved_env {
        let _ = writeln!(out, "{key}={value}");
    }

    Ok(out)
}

/// Return the canonical env file path for the given instance name.
#[must_use]
pub fn env_path(instance_name: &str) -> std::path::PathBuf {
    let home = std::env::var("HOME").unwrap_or_else(|_| "/root".to_string());
    std::path::PathBuf::from(format!(
        "{home}/.config/containers/systemd/{instance_name}.env",
    ))
}

#[cfg(test)]
mod tests {
    use super::*;
    use fs_node_core::{
        config::service::{
            Constraints, ContainerDef, ModuleRoles, ModuleUi, ServiceClass, ServiceContract,
            ServiceLifecycle, ServiceLoad, ServiceMeta, ServiceSetup, ServiceType,
        },
        state::desired::ServiceInstance,
    };
    use indexmap::IndexMap;
    use std::collections::HashMap;

    fn make_instance(name: &str, class_key: &str, env: HashMap<String, String>) -> ServiceInstance {
        ServiceInstance {
            name: name.to_string(),
            class_key: class_key.to_string(),
            class: ServiceClass {
                meta: ServiceMeta {
                    name: name.to_string(),
                    alias: vec![],
                    service_types: vec![ServiceType::Git],
                    author: None,
                    version: "1.0".to_string(),
                    tags: vec![],
                    description: None,
                    website: None,
                    repository: None,
                    port: 3000,
                    constraints: Constraints::default(),
                    federation: None,
                    health_path: None,
                    health_port: None,
                    health_scheme: None,
                    capabilities: vec![],
                    roles: ModuleRoles::default(),
                    ui: ModuleUi::default(),
                },
                vars: IndexMap::default(),
                load: ServiceLoad::default(),
                container: Some(ContainerDef {
                    name: name.to_string(),
                    image: format!("docker.io/{name}"),
                    image_tag: "latest".to_string(),
                    networks: vec![],
                    volumes: vec![],
                    published_ports: vec![],
                    healthcheck: None,
                    user: None,
                    read_only: false,
                    tmpfs: vec![],
                    security_opt: vec![],
                    ulimits: IndexMap::default(),
                }),
                service: None,
                variables: vec![],
                lifecycle: ServiceLifecycle::default(),
                environment: IndexMap::default(),
                setup: ServiceSetup::default(),
                contract: ServiceContract::default(),
                manifest: None,
            },
            service_types: vec![ServiceType::Git],
            resolved_env: env,
            resolved_args: vec![],
            service_domain: format!("{name}.example.com"),
            alias_domains: vec![],
            sub_services: vec![],
            version: "1.0".to_string(),
            resolved_volumes: vec![],
            capabilities: vec![],
        }
    }

    #[test]
    fn env_file_contains_key_value_pairs() {
        let mut env = HashMap::new();
        env.insert("GIT_HOST".to_string(), "forgejo".to_string());
        env.insert("GIT_PORT".to_string(), "3000".to_string());
        let out = generate(&make_instance("forgejo", "git/forgejo", env)).unwrap();
        assert!(out.contains("GIT_HOST=forgejo"));
        assert!(out.contains("GIT_PORT=3000"));
    }

    #[test]
    fn env_file_has_header_with_class_key() {
        let out = generate(&make_instance("forgejo", "git/forgejo", HashMap::new())).unwrap();
        assert!(out.contains("# Generated by fsn"));
        assert!(out.contains("git/forgejo"));
    }

    #[test]
    fn env_file_is_empty_for_no_env_vars() {
        let out = generate(&make_instance("forgejo", "git/forgejo", HashMap::new())).unwrap();
        // Header exists but no KEY=VALUE lines beyond it
        let non_comment_lines: Vec<_> = out
            .lines()
            .filter(|l| !l.starts_with('#') && !l.is_empty())
            .collect();
        assert!(non_comment_lines.is_empty());
    }
}
